# Generated by Django 4.2.6 on 2024-04-05 16:06

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('locations', models.PositiveSmallIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=core.models.profile_upload_path, verbose_name='location image')),
                ('description', models.TextField(default=None, verbose_name='description')),
                ('country', django_countries.fields.CountryField(blank=True, default='it', max_length=2)),
                ('region', models.CharField(max_length=255, verbose_name='regione')),
                ('province', models.CharField(max_length=255, verbose_name='provincie')),
                ('city', models.CharField(max_length=255, verbose_name='cita')),
                ('zip_code', models.CharField(max_length=5, verbose_name='CAP')),
                ('street_name', models.CharField(max_length=255, verbose_name='via')),
                ('street_number', models.PositiveSmallIntegerField(verbose_name='numero civico')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='nome giorno settimana')),
                ('start', models.TimeField(verbose_name='ora inizio')),
                ('fine', models.TimeField(verbose_name='ora fine')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location_schedule', to='core.location')),
            ],
            options={
                'verbose_name': 'orario apertura',
                'verbose_name_plural': 'orari apertura',
            },
        ),
        migrations.AddConstraint(
            model_name='orari',
            constraint=models.UniqueConstraint(fields=('weekday', 'start', 'location'), name='unique_day_start'),
        ),
        migrations.AlterIndexTogether(
            name='orari',
            index_together={('weekday', 'start')},
        ),
    ]
