# Generated by Django 5.0.6 on 2024-06-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smdmanager_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location_turni', to='core.location'),
        ),
    ]
